#!/usr/bin/env bash
# Cloud Agent start phase — per-boot reconciliation of runtime services.
# Must be idempotent, avoid duplicate processes, reach readiness, then return.
# Long-running foreground processes (the dev server) live in `terminals`, not here.
#
# Cursor launches `start` detached and does not block `terminals`. The dev
# terminal runs `bash .cursor/start.sh --wait` so Next.js starts only after
# this script writes its exit code (env, Docker, MongoDB PRIMARY, Prisma, seed).
set -euo pipefail

cd "$(dirname "$0")/.."

STATUS_FILE="/tmp/stockly-start.status"

if [ "${1:-}" = "--wait" ]; then
  echo "==> [dev] Waiting for start.sh (Docker, MongoDB, Prisma, seed)"
  until [ -f "$STATUS_FILE" ]; do sleep 1; done
  while [ "$(cat "$STATUS_FILE" 2>/dev/null || true)" = "pending" ]; do sleep 1; done
  status="$(tr -dc '0-9' < "$STATUS_FILE" || true)"
  if [ "${status}" != "0" ]; then
    echo "start.sh failed with status ${status:-unknown}; not starting Next.js"
    exit 1
  fi
  exit 0
fi

# Claim the boot immediately so a stale status cannot release the terminal.
printf 'pending\n' > "$STATUS_FILE"
trap 'printf "%s\n" "$?" > "$STATUS_FILE"' EXIT

MONGO_CONTAINER="stockly-mongo"
MONGO_VOLUME="stockly-mongo-data"

echo "==> [start] Ensure .env (local dev defaults; .env is gitignored)"
if [ ! -f .env ]; then
  JWT="$(openssl rand -hex 32)"
  cat > .env <<EOF
# Generated by .cursor/start.sh for local Cloud Agent development.
# See .env.example for the full list of optional integration variables.
DATABASE_URL="mongodb://localhost:27017/stockly?replicaSet=rs0"
JWT_SECRET="$JWT"
NEXT_PUBLIC_API_URL="http://localhost:3000"
EOF
fi

# Export .env into this shell so child processes (the tsx seed script in
# particular) receive DATABASE_URL. tsx does not auto-load .env, unlike the
# Prisma CLI and Next.js, so the seed would otherwise fail on a fresh DB.
set -a
# shellcheck disable=SC1091
. ./.env
set +a

echo "==> [start] Ensure Docker daemon is running (fuse-overlayfs storage driver)"
if ! sudo docker info >/dev/null 2>&1; then
  sudo bash -c 'nohup dockerd --storage-driver=fuse-overlayfs >/var/log/dockerd.log 2>&1 &'
  for _ in $(seq 1 30); do sudo docker info >/dev/null 2>&1 && break; sleep 1; done
fi
sudo docker info >/dev/null 2>&1 || { echo "dockerd failed to start"; exit 1; }

echo "==> [start] Ensure MongoDB single-node replica set container"
if sudo docker ps -a --format '{{.Names}}' | grep -qx "$MONGO_CONTAINER"; then
  sudo docker start "$MONGO_CONTAINER" >/dev/null
else
  sudo docker run -d --name "$MONGO_CONTAINER" -p 27017:27017 \
    -v "$MONGO_VOLUME":/data/db mongo:7 --replSet rs0 --bind_ip_all >/dev/null
fi

echo "==> [start] Wait for mongod to accept connections"
for _ in $(seq 1 60); do
  sudo docker exec "$MONGO_CONTAINER" mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok' 2>/dev/null | grep -q 1 && break
  sleep 1
done
sudo docker exec "$MONGO_CONTAINER" mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok' 2>/dev/null | grep -q 1 || { echo "mongod failed to accept connections"; exit 1; }

echo "==> [start] Ensure replica set initiated (transactions require a replica set)"
sudo docker exec "$MONGO_CONTAINER" mongosh --quiet --eval \
  'try { rs.status().ok } catch (e) { rs.initiate({ _id: "rs0", members: [{ _id: 0, host: "localhost:27017" }] }) }' >/dev/null

echo "==> [start] Wait for PRIMARY"
for _ in $(seq 1 60); do
  sudo docker exec "$MONGO_CONTAINER" mongosh --quiet --eval 'db.hello().isWritablePrimary' 2>/dev/null | grep -q true && break
  sleep 1
done
sudo docker exec "$MONGO_CONTAINER" mongosh --quiet --eval 'db.hello().isWritablePrimary' 2>/dev/null | grep -q true || { echo "MongoDB replica set failed to reach PRIMARY"; exit 1; }

echo "==> [start] Sync Prisma schema (indexes) to MongoDB"
npx prisma db push --skip-generate

echo "==> [start] Seed demo data if the database is empty"
USER_COUNT="$(sudo docker exec "$MONGO_CONTAINER" mongosh stockly --quiet --eval 'db.User.countDocuments()' 2>/dev/null | tr -dc '0-9')"
if [ "${USER_COUNT:-0}" = "0" ]; then
  npm run script:reset-demo-db -- --with-catalog --skip-redis
else
  echo "   Database already has ${USER_COUNT} users — skipping seed"
fi

echo "==> [start] Done. Demo logins: test@admin.com / test@client.com / test@supplier.com (password 12345678)"
